---
- hosts: 172.31.39.214
  become: yes
  tasks:
  - name: i want to execute any linux command
    command: hostname -f
    register: myfirsttaskresult

  - name: i want to display myfirsttaskresult 
    debug:
       msg: "{{myfirsttaskresult}}"
       
  